// auth
export const CREATE_TOKEN = 'CREATE_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';
//edit
export const CREATE_ARTICLE = 'CREATE_ARITCLE'
export const SAVE_ARTICLE = 'SAVE_ARITCLE'
export const CHANGE_ARTICLE = 'CHANGE_ARITCLE'
export const PUBLISH_ARTICLE = 'PUBLISH_ARTICLE'
export const NOT_PUBLISH_ARTICLE = 'NOT_PUBLISH_ARTICLE'
export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES'
export const GET_CURRENT_ARTICLE = 'GET_CURRENT_ARTICLE'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
//tag
export const CREATE_TAG = 'CREATE_TAG'
export const MODIFY_TAG = 'MODIFY_TAG'
export const DELETE_TAG = 'DELETE_TAG'
export const DELETE_CURRENT_TAG = 'DELETE_CURRENT_TAG'
export const GET_ALL_TAGS = 'GET_ALL_TAGS'
export const TOGGLE_SELECT_TAG = 'TOGGLE_SELECT_TAG'
export const CLEAR_SELECT_TAG = 'CLEAR_SELECT_TAG'
//page
export const GET_ALL_PAGE = 'GET_ALL_PAGE'
export const GET_CUR_PAGE = 'GET_CUR_PAGE'
