// auth
export const CREATE_TOKEN = 'CREATE_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';

//edit
export const CREATE_ARTICLE = 'CREATE_ARITCLE'
export const SAVE_ARTICLE = 'SAVE_ARITCLE'
export const CHANGE_ARTICLE = 'CHANGE_ARITCLE'
export const PUBLISH_ARTICLE = 'PUBLISH_ARTICLE'
export const NOT_PUBLISH_ARTICLE = 'NOT_PUBLISH_ARTICLE'
export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES'
export const GET_CURRENT_ARTICLE = 'GET_CURRENT_ARTICLE'
export const DELETE_ARTICLE = 'DELETE_ARTICLE'
